services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        PROD_BUILD: "true"
    restart: unless-stopped
    ports:
      - "5000:80"
    volumes:
      - .env:/app/.env:ro
