services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        PROD_BUILD: "true"
    restart: unless-stopped
    ports:
      - "5000:80"
    environment:
      - HF_HOME=/.cache/huggingface
    volumes:
      - .env:/app/.env:ro
      - ./hf_cache:/.cache/huggingface:rw
