services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        PROD_BUILD: "true"
    restart: unless-stopped
    ports:
      - "5000:80"
    environment:
      - HF_HOME=/.cache/huggingface
      - FLAIR_CACHE_ROOT=/.cache/flair
      - NLTK_DATA=/root/nltk_data
      - GUNICORN_WORKERS=1
      - GUNICORN_WORKER_CLASS=gthread
    volumes:
      - .env:/app/.env:ro
      - ./hf_cache:/.cache/huggingface:rw
      - ./flair_cache:/.cache/flair:rw
      - ./nltk_cache:/root/nltk_data:rw
